/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sabor.view;

/**
 *
 * @author dutra
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        // 1. Limpa o painel para não duplicar se a tela for reaberta
        painelListaClientes.removeAll();

// 2. Configurações do Layout para o Scroll funcionar
// O BoxLayout.Y_AXIS empilha os cards um embaixo do outro
        painelListaClientes.setLayout(new javax.swing.BoxLayout(painelListaClientes, javax.swing.BoxLayout.Y_AXIS));

// Define um tamanho preferencial grande para que o JScrollPane entenda que tem conteúdo para rolar
        painelListaClientes.setPreferredSize(new java.awt.Dimension(290, 10000));
        painelListaClientes.setMinimumSize(new java.awt.Dimension(290, 384));

// 3. Adicionando os cards de teste (baseado no seu print)
        adicionarCardCliente("Serephynna dos Santos", "rua tal 123, tel, Porto Alegre", "51 12233-4455", "2500,00");
        adicionarCardCliente("Giselisson Soares", "rua tal 123, tel, Porto Alegre", "51 12233-4455", "2500,00");
        adicionarCardCliente("Claudiano da Silva", "rua tal 123, tel, Porto Alegre", "51 12233-4455", "2500,00");

// 4. "Sacudida" final para atualizar a interface visualmente
        painelListaClientes.revalidate();
        painelListaClientes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void adicionarCardCliente(String nome, String endereco, String telefone, String totalCompras) {
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setBackground(new java.awt.Color(255, 249, 230)); // Bege claro
        card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true)); // Borda dourada fina

        // Configuração de tamanho para o ScrollPane
        card.setPreferredSize(new java.awt.Dimension(270, 110));
        card.setMinimumSize(new java.awt.Dimension(270, 110));
        card.setMaximumSize(new java.awt.Dimension(Short.MAX_VALUE, 110));
        card.setLayout(null);

        // Nome do Cliente (Título)
        javax.swing.JLabel lblNome = new javax.swing.JLabel("Cliente: " + nome);
        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 16));
        lblNome.setBounds(15, 10, 400, 25);
        card.add(lblNome);

        // Endereço
        javax.swing.JLabel lblEnd = new javax.swing.JLabel("Endereço: " + endereco);
        lblEnd.setFont(new java.awt.Font("Segoe UI", 0, 13));
        lblEnd.setForeground(new java.awt.Color(80, 80, 80));
        lblEnd.setBounds(15, 35, 400, 20);
        card.add(lblEnd);

        // Telefone
        javax.swing.JLabel lblTel = new javax.swing.JLabel("Telefone: " + telefone);
        lblTel.setFont(new java.awt.Font("Segoe UI", 0, 13));
        lblTel.setForeground(new java.awt.Color(80, 80, 80));
        lblTel.setBounds(15, 55, 400, 20);
        card.add(lblTel);

        // Total em Compras (Destaque)
        javax.swing.JLabel lblTotal = new javax.swing.JLabel("Total em Compras: R$ " + totalCompras);
        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 13));
        lblTotal.setForeground(new java.awt.Color(100, 100, 100));
        lblTotal.setBounds(15, 75, 400, 20);
        card.add(lblTotal);

        // Adição ao painel que está dentro do ScrollPane
        // Certifique-se de que o nome do seu painel de clientes seja 'painelListaClientes'
        painelListaClientes.add(card);

        // Espaçamento entre um card e outro
        painelListaClientes.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));

        // Atualiza a interface
        painelListaClientes.revalidate();
        painelListaClientes.repaint();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        btnEstoqueC = new javax.swing.JButton();
        btnTelaIniciaC1 = new javax.swing.JButton();
        btnClientesC = new javax.swing.JButton();
        btnEncomendaC = new javax.swing.JButton();
        btnRelatoriosC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarProduto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        painelListaClientes = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLayeredPane1.setBackground(new java.awt.Color(197, 107, 107));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93)));
        jLayeredPane1.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabor/view/logo3.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnEstoqueC.setBackground(new java.awt.Color(255, 153, 153));
        btnEstoqueC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEstoqueC.setForeground(new java.awt.Color(0, 0, 0));
        btnEstoqueC.setText("Estoque");
        btnEstoqueC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueCActionPerformed(evt);
            }
        });

        btnTelaIniciaC1.setBackground(new java.awt.Color(255, 153, 153));
        btnTelaIniciaC1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTelaIniciaC1.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaIniciaC1.setText("Tela Inicial");
        btnTelaIniciaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaIniciaC1ActionPerformed(evt);
            }
        });

        btnClientesC.setBackground(new java.awt.Color(191, 160, 93));
        btnClientesC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClientesC.setForeground(new java.awt.Color(0, 0, 0));
        btnClientesC.setText("Clientes");
        btnClientesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesCActionPerformed(evt);
            }
        });

        btnEncomendaC.setBackground(new java.awt.Color(255, 153, 153));
        btnEncomendaC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEncomendaC.setForeground(new java.awt.Color(0, 0, 0));
        btnEncomendaC.setText("Encomendas");
        btnEncomendaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomendaCActionPerformed(evt);
            }
        });

        btnRelatoriosC.setBackground(new java.awt.Color(255, 153, 153));
        btnRelatoriosC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatoriosC.setForeground(new java.awt.Color(0, 0, 0));
        btnRelatoriosC.setText("Relatórios");
        btnRelatoriosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosCActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEstoqueC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnTelaIniciaC1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnClientesC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEncomendaC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRelatoriosC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRelatoriosC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncomendaC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientesC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstoqueC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelaIniciaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnTelaIniciaC1)
                .addGap(18, 18, 18)
                .addComponent(btnEstoqueC)
                .addGap(18, 18, 18)
                .addComponent(btnEncomendaC)
                .addGap(18, 18, 18)
                .addComponent(btnClientesC)
                .addGap(18, 18, 18)
                .addComponent(btnRelatoriosC)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro de clientes");

        txtBuscarProduto.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarProduto.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarProduto.setText("Buscar Cliente");
        txtBuscarProduto.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Editar");

        painelListaClientes.setBackground(new java.awt.Color(204, 204, 204));
        painelListaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93), 2));
        painelListaClientes.setLayout(new javax.swing.BoxLayout(painelListaClientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(painelListaClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1)))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstoqueCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstoqueCActionPerformed

    private void btnTelaIniciaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaIniciaC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelaIniciaC1ActionPerformed

    private void btnClientesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesCActionPerformed

    private void btnEncomendaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomendaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncomendaCActionPerformed

    private void btnRelatoriosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesC;
    private javax.swing.JButton btnEncomendaC;
    private javax.swing.JButton btnEstoqueC;
    private javax.swing.JButton btnRelatoriosC;
    private javax.swing.JButton btnTelaIniciaC1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelListaClientes;
    private javax.swing.JTextField txtBuscarProduto;
    // End of variables declaration//GEN-END:variables
}
