/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sabor.view;

import br.com.sabor.controller.Navegador;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author dutra
 */
public class TelaInicial extends javax.swing.JFrame {

    private static TelaEstoque telaEstoqueUnica;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        atualizarTabelaEstoqueBaixo();
        exibirFaturamento();
    }

    //metodo para tabela de estoque abixo
    public void atualizarTabelaEstoqueBaixo() {
        br.com.sabor.dao.ProdutoDAO dao = new br.com.sabor.dao.ProdutoDAO();
        List<br.com.sabor.model.Produto> lista = dao.listarEstoqueBaixo();
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProdutoBaixo.getModel();

        modelo.setNumRows(0);

        for (br.com.sabor.model.Produto p : lista) {
            double subtotal = p.getValorUni() * p.getQuantidade();

            modelo.addRow(new Object[]{
                p.getNomeProduto(),
                p.getQuantidade(),
                String.format("R$ %.2f", subtotal)
            });
        }
    }

    private void exibirFaturamento() {
        try {
            br.com.sabor.dao.EncomendaDAO dao = new br.com.sabor.dao.EncomendaDAO();
            double total = dao.consultarFaturamentoSemanal();

            // Verifique se o nome da sua label é lblFaturamento ou outro
            lblFaturamento.setText(String.format("R$ %.2f", total));
        } catch (Exception e) {
            lblFaturamento.setText("R$ 0,00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        btnTelaInicialTI = new javax.swing.JButton();
        btnEstoqueTI = new javax.swing.JButton();
        btnEncomendasTI = new javax.swing.JButton();
        TelaClientesTI = new javax.swing.JButton();
        btnRelatoriosTI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNovaVendaTI = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblFaturamento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutoBaixo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pFundo.setBackground(new java.awt.Color(204, 204, 204));
        pFundo.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(197, 107, 107));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93)));

        btnTelaInicialTI.setBackground(new java.awt.Color(191, 160, 93));
        btnTelaInicialTI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTelaInicialTI.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaInicialTI.setText("Tela Inicial");
        btnTelaInicialTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialTIActionPerformed(evt);
            }
        });

        btnEstoqueTI.setBackground(new java.awt.Color(255, 153, 153));
        btnEstoqueTI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEstoqueTI.setForeground(new java.awt.Color(0, 0, 0));
        btnEstoqueTI.setText("Estoque");
        btnEstoqueTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueTIActionPerformed(evt);
            }
        });

        btnEncomendasTI.setBackground(new java.awt.Color(255, 153, 153));
        btnEncomendasTI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEncomendasTI.setForeground(new java.awt.Color(0, 0, 0));
        btnEncomendasTI.setText("Encomendas");
        btnEncomendasTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomendasTIActionPerformed(evt);
            }
        });

        TelaClientesTI.setBackground(new java.awt.Color(255, 153, 153));
        TelaClientesTI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TelaClientesTI.setForeground(new java.awt.Color(0, 0, 0));
        TelaClientesTI.setText("Clientes");
        TelaClientesTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaClientesTIActionPerformed(evt);
            }
        });

        btnRelatoriosTI.setBackground(new java.awt.Color(255, 153, 153));
        btnRelatoriosTI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatoriosTI.setForeground(new java.awt.Color(0, 0, 0));
        btnRelatoriosTI.setText("Relatórios");
        btnRelatoriosTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosTIActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dutra\\Documents\\PI\\Sabor-em-Ordem\\src\\main\\java\\br\\com\\sabor\\view\\logo3.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEstoqueTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTelaInicialTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TelaClientesTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRelatoriosTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEncomendasTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnTelaInicialTI)
                .addGap(18, 18, 18)
                .addComponent(btnEstoqueTI)
                .addGap(18, 18, 18)
                .addComponent(btnEncomendasTI)
                .addGap(18, 18, 18)
                .addComponent(TelaClientesTI)
                .addGap(18, 18, 18)
                .addComponent(btnRelatoriosTI)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(197, 107, 107));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resumo Semanal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnNovaVendaTI.setBackground(new java.awt.Color(255, 153, 153));
        btnNovaVendaTI.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNovaVendaTI.setForeground(new java.awt.Color(0, 0, 0));
        btnNovaVendaTI.setText("Nova Venda");
        btnNovaVendaTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaTIActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93), 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Faturamento:");

        lblFaturamento.setBackground(new java.awt.Color(191, 160, 93));
        lblFaturamento.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblFaturamento.setForeground(new java.awt.Color(191, 160, 93));
        lblFaturamento.setText("RS 00,00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFaturamento)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(117, 117, 117))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFaturamento)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        tblProdutoBaixo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblProdutoBaixo);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estoque baixo");

        pFundo.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pFundo.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pFundo.setLayer(btnNovaVendaTI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pFundo.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pFundo.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pFundo.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pFundo.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pFundoLayout = new javax.swing.GroupLayout(pFundo);
        pFundo.setLayout(pFundoLayout);
        pFundoLayout.setHorizontalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFundoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFundoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFundoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pFundoLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pFundoLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnNovaVendaTI))
                    .addGroup(pFundoLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel6)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pFundoLayout.setVerticalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFundoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4))
                    .addGroup(pFundoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnNovaVendaTI)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaVendaTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaTIActionPerformed
        CadastrarVenda dialog = new CadastrarVenda(new javax.swing.JFrame(), true, null);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNovaVendaTIActionPerformed

    private void btnRelatoriosTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosTIActionPerformed
        Navegador.navegar(this, new Relatorio());
    }//GEN-LAST:event_btnRelatoriosTIActionPerformed

    private void btnEstoqueTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueTIActionPerformed
        Navegador.navegar(this, new TelaEstoque());
    }//GEN-LAST:event_btnEstoqueTIActionPerformed

    private void btnTelaInicialTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelaInicialTIActionPerformed

    private void btnEncomendasTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomendasTIActionPerformed
        Navegador.navegar(this, new TelaEncomendas(null));
    }//GEN-LAST:event_btnEncomendasTIActionPerformed

    private void TelaClientesTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaClientesTIActionPerformed
        Navegador.navegar(this, new TelaClientes());
    }//GEN-LAST:event_TelaClientesTIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TelaClientesTI;
    private javax.swing.JButton btnEncomendasTI;
    private javax.swing.JButton btnEstoqueTI;
    private javax.swing.JButton btnNovaVendaTI;
    private javax.swing.JButton btnRelatoriosTI;
    private javax.swing.JButton btnTelaInicialTI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFaturamento;
    private javax.swing.JLayeredPane pFundo;
    private javax.swing.JTable tblProdutoBaixo;
    // End of variables declaration//GEN-END:variables
}
