/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sabor.view;

import br.com.sabor.controller.Navegador;
import br.com.sabor.dao.ClienteDAO;
import br.com.sabor.model.Clientes;
import java.util.List;

/**
 *
 * @author dutra
 */
public class TelaClientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    private Long idClienteSelecionado = null;

    public TelaClientes() {
        initComponents();
        carregarCardsDosClientes();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // card cleinte
    private void adicionarCardCliente(Long id, String nome, String endereco, String telefone) {
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setBackground(new java.awt.Color(255, 249, 230)); // Cor bege padrão
        card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        card.setPreferredSize(new java.awt.Dimension(270, 100));
        card.setMaximumSize(new java.awt.Dimension(Short.MAX_VALUE, 100));
        card.setLayout(null);

        //logica de seleção
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idClienteSelecionado = id;

                for (java.awt.Component c : painelListaClientes.getComponents()) {
                    if (c instanceof javax.swing.JPanel) {
                        c.setBackground(new java.awt.Color(255, 249, 230));
                    }
                }
                card.setBackground(new java.awt.Color(255, 215, 120));
            }
        });

        // Labels 
        javax.swing.JLabel lblNome = new javax.swing.JLabel("Cliente: " + nome);
        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 15));
        lblNome.setBounds(15, 10, 240, 25);
        card.add(lblNome);

        javax.swing.JLabel lblEnd = new javax.swing.JLabel("Endereço: " + endereco);
        lblEnd.setFont(new java.awt.Font("Segoe UI", 0, 13));
        lblEnd.setBounds(15, 35, 240, 20);
        card.add(lblEnd);

        javax.swing.JLabel lblTel = new javax.swing.JLabel("Telefone: " + telefone);
        lblTel.setFont(new java.awt.Font("Segoe UI", 0, 13));
        lblTel.setBounds(15, 55, 240, 20);
        card.add(lblTel);

        painelListaClientes.add(card);
        painelListaClientes.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
    }

    // carregar dados 
    public void carregarCardsDosClientes() {
        painelListaClientes.removeAll();
        try {
            br.com.sabor.dao.ClienteDAO dao = new br.com.sabor.dao.ClienteDAO();
            List<br.com.sabor.model.Clientes> lista = dao.listarTodos();

            for (br.com.sabor.model.Clientes c : lista) {
                adicionarCardCliente(c.getId(), c.getNomeCliente(), c.getEndereco(), c.getTelefone());
            }
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
        painelListaClientes.revalidate();
        painelListaClientes.repaint();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        btnEstoqueC = new javax.swing.JButton();
        btnTelaIniciaC1 = new javax.swing.JButton();
        btnClientesC = new javax.swing.JButton();
        btnEncomendaC = new javax.swing.JButton();
        btnRelatoriosC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        painelListaClientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLayeredPane1.setBackground(new java.awt.Color(197, 107, 107));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93)));
        jLayeredPane1.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dutra\\Documents\\PI\\Sabor-em-Ordem\\src\\main\\java\\br\\com\\sabor\\view\\logo3.png")); // NOI18N
        jLabel2.setText("jLabel2");

        btnEstoqueC.setBackground(new java.awt.Color(255, 153, 153));
        btnEstoqueC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEstoqueC.setForeground(new java.awt.Color(0, 0, 0));
        btnEstoqueC.setText("Estoque");
        btnEstoqueC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueCActionPerformed(evt);
            }
        });

        btnTelaIniciaC1.setBackground(new java.awt.Color(255, 153, 153));
        btnTelaIniciaC1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTelaIniciaC1.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaIniciaC1.setText("Tela Inicial");
        btnTelaIniciaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaIniciaC1ActionPerformed(evt);
            }
        });

        btnClientesC.setBackground(new java.awt.Color(191, 160, 93));
        btnClientesC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClientesC.setForeground(new java.awt.Color(0, 0, 0));
        btnClientesC.setText("Clientes");
        btnClientesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesCActionPerformed(evt);
            }
        });

        btnEncomendaC.setBackground(new java.awt.Color(255, 153, 153));
        btnEncomendaC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEncomendaC.setForeground(new java.awt.Color(0, 0, 0));
        btnEncomendaC.setText("Encomendas");
        btnEncomendaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomendaCActionPerformed(evt);
            }
        });

        btnRelatoriosC.setBackground(new java.awt.Color(255, 153, 153));
        btnRelatoriosC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatoriosC.setForeground(new java.awt.Color(0, 0, 0));
        btnRelatoriosC.setText("Relatórios");
        btnRelatoriosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosCActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEstoqueC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnTelaIniciaC1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnClientesC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEncomendaC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRelatoriosC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRelatoriosC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncomendaC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientesC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstoqueC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelaIniciaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnTelaIniciaC1)
                .addGap(18, 18, 18)
                .addComponent(btnEstoqueC)
                .addGap(18, 18, 18)
                .addComponent(btnEncomendaC)
                .addGap(18, 18, 18)
                .addComponent(btnClientesC)
                .addGap(18, 18, 18)
                .addComponent(btnRelatoriosC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro de clientes");

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setOpaque(true);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 153, 153));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        painelListaClientes.setBackground(new java.awt.Color(204, 204, 204));
        painelListaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 160, 93), 2));
        painelListaClientes.setLayout(new javax.swing.BoxLayout(painelListaClientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(painelListaClientes);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Buscar cliente por nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnEditar)))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstoqueCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueCActionPerformed
        Navegador.navegar(this, new TelaEstoque());
    }//GEN-LAST:event_btnEstoqueCActionPerformed

    private void btnTelaIniciaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaIniciaC1ActionPerformed
        Navegador.navegar(this, new TelaInicial());
    }//GEN-LAST:event_btnTelaIniciaC1ActionPerformed

    private void btnClientesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesCActionPerformed

    private void btnEncomendaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomendaCActionPerformed
        Navegador.navegar(this, new TelaEncomendas(null));
    }//GEN-LAST:event_btnEncomendaCActionPerformed

    private void btnRelatoriosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosCActionPerformed
        Navegador.navegar(this, new Relatorio());
    }//GEN-LAST:event_btnRelatoriosCActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (idClienteSelecionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente primeiro!");
            return;
        }

        try {
            br.com.sabor.dao.ClienteDAO dao = new br.com.sabor.dao.ClienteDAO();
            br.com.sabor.model.Clientes clienteSelecionado = dao.buscarPorId(idClienteSelecionado);

            // cria a tela de edição
            EditarCliente telaEdit = new EditarCliente();

            // preenche os campos dela
            telaEdit.preencherCamposParaEdicao(clienteSelecionado);

            telaEdit.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    carregarCardsDosClientes();
                }
            });
            telaEdit.setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // 1. Limpa o painel antes de mostrar os novos resultados
        painelListaClientes.removeAll();

        try {
            // 2. Instancia o DAO e busca pelo nome digitado
            br.com.sabor.dao.ClienteDAO dao = new br.com.sabor.dao.ClienteDAO();
            List<br.com.sabor.model.Clientes> lista = dao.buscarPorNome(txtBuscar.getText());

            // 3. Usa o SEU método para criar os cards na tela
            for (br.com.sabor.model.Clientes c : lista) {
                adicionarCardCliente(c.getId(), c.getNomeCliente(), c.getEndereco(), c.getTelefone());
            }

        } catch (Exception e) {
            System.err.println("Erro na busca: " + e.getMessage());
        }

        // 4. Avisa o Java para redesenhar a tela com os novos cards
        painelListaClientes.revalidate();
        painelListaClientes.repaint();
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesC;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEncomendaC;
    private javax.swing.JButton btnEstoqueC;
    private javax.swing.JButton btnRelatoriosC;
    private javax.swing.JButton btnTelaIniciaC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelListaClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
